name: maxit
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:3.13-management
  file-storage:
    image: seber/maxit-file-storage:latest
    environment:
      - APP_PORT=8888
  backend:
    image: maxit/backend:latest
    depends_on:
      - rabbitmq
      - file-storage
      - db
    environment:
      - JWT_SECRET_KEY=
      - QUEUE_HOST=rabbitmq
      - QUEUE_PORT=5672
      - QUEUE_USER=guest
      - QUEUE_PASSWORD=guest
      - APP_PORT=8000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=maxit
      - FILE_STORAGE_HOST=file-storage
      - FILE_STORAGE_PORT=8888
  db:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: maxit
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
  worker:
    image: seber/maxit-worker:latest
    depends_on:
      - rabbitmq
      - db
      - backend
      - file-storage
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jobs-data:/tmp
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - DOCKER_HOST=unix:///var/run/docker.sock
      - JOBS_DATA_VOLUME=jobs-data
      - RESPONSE_QUEUE_NAME=worker_response_queue
      - WORKER_QUEUE_NAME=worker_queue
  frontend:
    image: maxit/frontend:latest
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000/api/v1
      - ORIGIN=https://mini-maxit.pl
    expose:
      - "3000"
volumes:
  file-storage-media:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./volumes/file-storage-media
  jobs-data:
  pgdata:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./volumes/pgdata
